# Generated by Django 5.2.9 on 2025-12-26 10:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ('-issued_at',)},
        ),
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='receipt',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='UTC timestamp when receipt was issued'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='signature',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='receipt',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Denormalized station for quick verification', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.station'),
        ),
    ]
