# Generated by Django 5.2.9 on 2025-12-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_receipt_options_receipt_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pump',
            options={'ordering': ('station', 'pump_number'), 'verbose_name': 'Pump', 'verbose_name_plural': 'Pumps'},
        ),
        migrations.AddField(
            model_name='pump',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last seen timestamp from pump/agent or events', null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pump',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('maintenance', 'maintenance')], default='online', help_text='Logical pump status', max_length=16),
        ),
    ]
