# Generated by Django 5.2.9 on 2025-12-27 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pump_options_pump_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomaly',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='anomaly',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.pump'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='rule',
            field=models.CharField(blank=True, help_text='Rule slug that created this anomaly', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.station'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['station'], name='core_anomal_station_5f944a_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['pump'], name='core_anomal_pump_id_46dc01_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['transaction'], name='core_anomal_transac_0ec8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['rule'], name='core_anomal_rule_0db16e_idx'),
        ),
    ]
