# Generated by Django 5.2.9 on 2025-12-27 19:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_anomaly_options_anomaly_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_l', models.DecimalField(decimal_places=3, help_text='Reported current liters in tank', max_digits=12)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, help_text='device/manual', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.tank')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
    ]
